### ISSUE TITLE
Some questions 

### ISSUE THREAD

**Issue by BuckTheWeasel** [asiekierka/SplashAnimationMC#1]
Hi 
i have some questions about the mod:

1."Put your animation frames in animation/000.png, animation/001.png, ... up to the amount of frames you want to have."  where is the map located in the  minecraft dir/config dir/mods dir? also can't find it.

2. what is the max resolution supported ?

3. how much frames can i use ? 

4. can i only use png and not jpg ?

thank for you time.
Buck

**Comment by asiekierka** [comment]
1. You have to create it in the minecraft directory.

2. The only limit is what your GPU can handle - up to 4096x4096 should be safe.

3. No limit, but more frames consume more RAM (for now - this will change).

4. Yes, only PNG is supported for now. Support for other formats is planned.
