### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Xaikii** [asiekierka/SplashAnimationMC#2]
1. Make the Animation Repeatable
2. Scale the Image / Or Allignment

The Animation does only play when the pack started, I think that's a bit sad since it is also only running once.
Also I created my animation in 2000x2000 (my standard resolution) and the animation is actually bigger than the screen

**Comment by asiekierka** [comment]
>1. Make the Animation Repeatable

This will not happen. Word of mouth says Mojang would prefer their logo staying on-screen for at least some amount of time.

>2. Scale the Image / Or Allignment

This is more likely to happen.

**Comment by Xaikii** [comment]
hmm, the Logo isn't even replaced(at least not that I've seen it) but I actually wante to just repeat the animation above the Mojang Logo
