### ISSUE TITLE
No animation plays (but there are images)

### ISSUE THREAD

**Issue by Ashen-Design** [asiekierka/SplashAnimationMC#3]
I'm having an issue where the images I've added aren't being located by the mod.

Screenshot of the images in the correct location:
![image](https://user-images.githubusercontent.com/40392749/43367563-e641ea6a-9346-11e8-9541-112c6fea54c2.png)

Screenshot of said images (852x480 resolution, correctly named, in the correct folder)
![image](https://user-images.githubusercontent.com/40392749/43367565-ef277b9a-9346-11e8-82db-72036db515a7.png)

I noticed in the log that it couldn't find the images:
`[15:46:24] [Thread-3/INFO] [STDERR]: [pl.asie.splashanimation.SplashAnimationRenderer:init:105]: Found no images!`

**Versions**
Forge: 14.23.4.2739
SplashAnimation: 0.1.0

**Comment by asiekierka** [comment]
The comment says "starting from 0". Try adding a "000.png".

**Comment by Ashen-Design** [comment]
Ah, that was the problem, thank you!
