### ISSUE TITLE
Update сode to 0.2.0

### ISSUE THREAD

**Issue by PixelmonPRO** [asiekierka/SplashAnimationMC#6]
Hello! Update сode to 0.2.0 versions! :)

**Comment by asiekierka** [comment]
https://git.asie.pl/asie-minecraft/SplashAnimation

**Comment by asiekierka** [comment]
Apologies for not updating the CF URL.

**Comment by PixelmonPRO** [comment]
@asiekierka At assembly: `Could not find com.elytradev:mini:0.2-SNAPSHOT`

**Comment by asiekierka** [comment]
Should be fixed now.
